src/jsws.js: replace mock webserver with a real node.js webserver.
The webserver currently returns a static 'Hello.' without checking the
filesystem; we change the test to request 'test.txtXXX' so that when we
have the server actually read the filesystem we should start to see that
test fail until we fix it.

diff --git a/Build b/Build
--- a/Build
+++ b/Build
@@ -1,17 +1,19 @@
 #!/bin/bash
 set -e
 trap '
-    [ ok = "$success" ] || err FAILED.
+    [ ok = "$success" ] || err FAILED.  # First, in case anything after fails.
+    [ -n "$test_server_pid" ] && kill "$test_server_pid"
 ' 0
 
 err() { echo 1>&2 "$@"; exit 1; }
 
 start_test_server() {
     local port="$1"
-    ({  cat src/test/http-header-200
-        cat src/test/docroot/test.txt
-    } | nc >/dev/null -l 127.0.0.1 $port
-    ) &
+    node src/jsws.js "$port" &
+    test_server_pid=$!
+    # XXX The server should properly daemonize and return only when it's
+    # able to set requests. Quick wait hack here until we get that working.
+    sleep 0.3
 }
 
 assert_equal() {
@@ -25,9 +27,10 @@ Expected: $expected
     }
 }
 
+assert_equal v5. "$(node --version | cut -c 1-3)"
 test_listen_port=12345
 start_test_server $test_listen_port
-actual="$(curl -S -s http://127.0.0.1:$test_listen_port/test.txt)"
+actual="$(curl -S -s http://127.0.0.1:$test_listen_port/test.txtXXX)"
 assert_equal Hello. "$actual"
 
 success=ok
